[package]
name = "brainfk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"

[profile.dev]
opt-level = 1

[profile.dev.pacakge."*"]
opt-level = 3
